//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServiceKlient.serwisy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serwisy.ModifySoap")]
    public interface ModifySoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        webServiceKlient.serwisy.HelloWorldResponse HelloWorld(webServiceKlient.serwisy.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceKlient.serwisy.HelloWorldResponse> HelloWorldAsync(webServiceKlient.serwisy.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name tekst from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modyfikacja", ReplyAction="*")]
        webServiceKlient.serwisy.ModyfikacjaResponse Modyfikacja(webServiceKlient.serwisy.ModyfikacjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modyfikacja", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceKlient.serwisy.ModyfikacjaResponse> ModyfikacjaAsync(webServiceKlient.serwisy.ModyfikacjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dodawanie", ReplyAction="*")]
        int Dodawanie(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dodawanie", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DodawanieAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public webServiceKlient.serwisy.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(webServiceKlient.serwisy.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceKlient.serwisy.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(webServiceKlient.serwisy.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModyfikacjaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modyfikacja", Namespace="http://tempuri.org/", Order=0)]
        public webServiceKlient.serwisy.ModyfikacjaRequestBody Body;
        
        public ModyfikacjaRequest() {
        }
        
        public ModyfikacjaRequest(webServiceKlient.serwisy.ModyfikacjaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModyfikacjaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tekst;
        
        public ModyfikacjaRequestBody() {
        }
        
        public ModyfikacjaRequestBody(string tekst) {
            this.tekst = tekst;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModyfikacjaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModyfikacjaResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceKlient.serwisy.ModyfikacjaResponseBody Body;
        
        public ModyfikacjaResponse() {
        }
        
        public ModyfikacjaResponse(webServiceKlient.serwisy.ModyfikacjaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModyfikacjaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModyfikacjaResult;
        
        public ModyfikacjaResponseBody() {
        }
        
        public ModyfikacjaResponseBody(string ModyfikacjaResult) {
            this.ModyfikacjaResult = ModyfikacjaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ModifySoapChannel : webServiceKlient.serwisy.ModifySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModifySoapClient : System.ServiceModel.ClientBase<webServiceKlient.serwisy.ModifySoap>, webServiceKlient.serwisy.ModifySoap {
        
        public ModifySoapClient() {
        }
        
        public ModifySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModifySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModifySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModifySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceKlient.serwisy.HelloWorldResponse webServiceKlient.serwisy.ModifySoap.HelloWorld(webServiceKlient.serwisy.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            webServiceKlient.serwisy.HelloWorldRequest inValue = new webServiceKlient.serwisy.HelloWorldRequest();
            inValue.Body = new webServiceKlient.serwisy.HelloWorldRequestBody();
            webServiceKlient.serwisy.HelloWorldResponse retVal = ((webServiceKlient.serwisy.ModifySoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceKlient.serwisy.HelloWorldResponse> webServiceKlient.serwisy.ModifySoap.HelloWorldAsync(webServiceKlient.serwisy.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceKlient.serwisy.HelloWorldResponse> HelloWorldAsync() {
            webServiceKlient.serwisy.HelloWorldRequest inValue = new webServiceKlient.serwisy.HelloWorldRequest();
            inValue.Body = new webServiceKlient.serwisy.HelloWorldRequestBody();
            return ((webServiceKlient.serwisy.ModifySoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceKlient.serwisy.ModyfikacjaResponse webServiceKlient.serwisy.ModifySoap.Modyfikacja(webServiceKlient.serwisy.ModyfikacjaRequest request) {
            return base.Channel.Modyfikacja(request);
        }
        
        public string Modyfikacja(string tekst) {
            webServiceKlient.serwisy.ModyfikacjaRequest inValue = new webServiceKlient.serwisy.ModyfikacjaRequest();
            inValue.Body = new webServiceKlient.serwisy.ModyfikacjaRequestBody();
            inValue.Body.tekst = tekst;
            webServiceKlient.serwisy.ModyfikacjaResponse retVal = ((webServiceKlient.serwisy.ModifySoap)(this)).Modyfikacja(inValue);
            return retVal.Body.ModyfikacjaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceKlient.serwisy.ModyfikacjaResponse> webServiceKlient.serwisy.ModifySoap.ModyfikacjaAsync(webServiceKlient.serwisy.ModyfikacjaRequest request) {
            return base.Channel.ModyfikacjaAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceKlient.serwisy.ModyfikacjaResponse> ModyfikacjaAsync(string tekst) {
            webServiceKlient.serwisy.ModyfikacjaRequest inValue = new webServiceKlient.serwisy.ModyfikacjaRequest();
            inValue.Body = new webServiceKlient.serwisy.ModyfikacjaRequestBody();
            inValue.Body.tekst = tekst;
            return ((webServiceKlient.serwisy.ModifySoap)(this)).ModyfikacjaAsync(inValue);
        }
        
        public int Dodawanie(int a, int b) {
            return base.Channel.Dodawanie(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DodawanieAsync(int a, int b) {
            return base.Channel.DodawanieAsync(a, b);
        }
    }
}
